### PR TITLE
All the articles together

### PR DESCRIPTION
**Pull request by cvdvalk**

### CODE REVIEW

**Comment by johnespinosa** [comment]
error line 7 haha use this!!!
http://jsonlint.com/

**Comment by cvdvalk** [comment]
works fine according to this one: http://jsonviewer.stack.hu/

**Comment by ghost** [comment]
Yes the same for me, no error..

**Comment by johnespinosa** [comment]
really? maybe I looked at the wrong fileee

**Comment by johnespinosa** [comment]
the very first object ends with:
        "organization" : "New York Times",
        "url" : "http://www.nytimes.com/2015/04/03/world/africa/garissa-university-college-shooting-in-kenya.html?ref=world&_r=1",
    },

**Comment by johnespinosa** [comment]
the comma can't be there after the url

**Comment by ghost** [comment]
Oh there is a mistake, i looked at the wrong file ;p

**Comment by johnespinosa** [comment]
yea so copy and paste that file into the link i gave and see if it hollers at you

**Comment by johnespinosa** [comment]
Then we'll be good to go :+1:

**Comment by cvdvalk** [comment]
ok i'll fix it

**Comment by cvdvalk** [comment]
It now passed validation.

**Comment by johnespinosa** [comment]
Great work!

**Pull request merged**
